version: "3"

services:
    postgres:
        image: postgres:latest
        env_file:
            - ./envs/prod.env
        volumes:
            - postgres_volume:/var/lib/postgresql/data

    backend:
        image: <path to the image compiled by GitLab CI/CD>:latest
        env_file:
            - ./envs/prod.env
        command: "sh /scripts/run.sh"
        depends_on:
            - postgres
        volumes:
            - static-files:/static-files
            - media-files:/media-files
            - frontend:/frontend/build

    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static-files:/static-files
            - media-files:/media-files
            - /etc/letsencrypt:/etc/letsencrypt
            - frontend:/frontend

volumes:
    postgres_volume:
    static-files:
    media-files:
    frontend:
